---
- name: Install EPEL Repository
  yum: name=epel-release state=present

- name: create electron-release-server directory
  file: path={{ WORKDIR }} state=directory recurse=yes
  #sudo: yes

- name: install git packages
  yum: name=git state=present

- name: checkout electron-release-server git repo
  git: repo=https://github.com/ArekSredzki/electron-release-server.git dest={{ WORKDIR }}
  #sudo: yes

- name: install curl repo
  raw: "curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -"

- name: Install latest nodejs
  yum: name={{item}} state=present
  with_items:
     - nodejs
     #- npm
     - gcc-c++
     - make

- name: copy file from template
  copy: src=/Users/gopinath/repo/ansible-gold/DevOps/roles/maya_electron/templates/local.j2 dest={{ WORKDIR }}/config/local.js owner=root group=root mode=0644 force=yes

- name: Install npm packages
  command: "npm install"
  args:
    chdir: /usr/src/electron-release-server

#- name: Clear Cache npm packages
#  command: "npm clear cache —-force"
#  args:
#    chdir: /usr/src/electron-release-server
- name: Install browserify packages
  command: "npm -g i browserify"
  args:
    chdir: /usr/src/electron-release-server

- name: Install Sails packages
  command: "npm install grunt-wiredep"
  args:
    chdir: /usr/src/electron-release-server

- name: Install Bower packages
  command: "npm install -g bower"
  args:
    chdir: /usr/src/electron-release-server


- name:  Bower -allow-root Install packages
  command: "bower install --allow-root"
  args:
    chdir: /usr/src/electron-release-server

- name: Install Sails packages
  command: "npm install sails"
  args:
    chdir: /usr/src/electron-release-server

- name: npm START  packages
  command: "npm start"
  args:
    chdir: /usr/src/electron-release-server



#npm -g i browserify
#npm install grunt-wiredep
#bower install --allow-root
